name: Topics and Methods in 21st Century Journalism
description: 'Instructor: <a href="http://sethmnookin.com" target="_blank">Seth Mnookin</a>. TR 12:30pm-2pm, <a href="http://whereis.mit.edu/?go=4">4-253</a>'
markdown: redcarpet
pygments: true
permalink: none
prose:
  rooturl: '_posts'
  siteurl: "http://smnookin.github.io/"
  relativeLinks: 'http://smnookin.github.io/links.jsonp'
  media: 'assets'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          placeholder: "Enter the name of the Author of this article"
      - name: "link"
        field:
          element: "text"
          label: "External Link"
          placeholder: "Enter link to an external article"
      - name: "displaydate"
        field:
          element: "text"
          label: "Publish Date"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Order"
          value: ""
      - name: "category"
        field:
          element: "select"
          label: "Genre"
          options:
            - name: "Science"
              value: "science"
            - name: "News"
              value: "politics"
            - name: "Features & Profiles"
              value: "arts"
            - name: "Course info"
              value: "course"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Reading"
              value: "reading"
            - name: "Student work"
              value: "student"
            - name: "Slider"
              value: "slider"
            - name: "1st image box on homepage"
              value: "image1"
            - name: "2nd image box on homepage" 
              value: "image2"
            - name: "3rd image box on homepage"
              value: "image3"
            - name: "Logistics and resources"
              value: "resources"              
            
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
